version: '3.7'

services:
  gateway:
    command: sh -c "hypercorn app.main:app --bind 0.0.0.0"
    build:
      context: ./gateway
      dockerfile: Dockerfile
    env_file:
      - ./gateway/.env
    ports:
      - "8001:8000"
    depends_on:
      - users
      - orders

  users:
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
    build:
      context: ./users
      dockerfile: Dockerfile
    env_file:
      - ./users/.env
    volumes:
      - ./users:/app

  orders:
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0"
    build:
      context: ./orders
      dockerfile: Dockerfile
    env_file:
      - ./orders/.env
    volumes:
      - ./orders:/app

#  product-service:
#    command: sh -c "hypercorn main:app --reload --host 0.0.0.0"
#    build:
#      context: ./product0-service
#      dockerfile: Dockerfile
#    env_file:
#      - ./product-service/.env
#    volumes:
#      - ./product-service/:/app/
#    environment:
#      - DATABASE_URI=postgresql+asyncpg://product_admin:product_admin@product_db/product_db_dev
#    depends_on:
#      - product_db
#
#  product-db:
#    image: postgres:12.1-alpine
#    volumes:
#      - postgres_data_product:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_USER=product_admin
#      - POSTGRES_PASSWORD=product_admin
#      - POSTGRES_DB=product_db_dev
#
#volumes:
#  postgres_data_product:
