version: '3.7'

services:
  auth-service:
    build: auth-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./auth-service/:/app/
    ports:
      - "8001:8000"
    depends_on:
      - auth-db

  auth-db:
    image: postgres:latest
    ports:
      - "5433:5433"
    volumes:
      - postgres_data_auth:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=auth_admin
      - POSTGRES_PASSWORD=auth_admin
      - POSTGRES_DB=auth_db_dev

  product-service:
    build: product-service
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - ./product-service/:/app/
    ports:
      - "8002:8000"
    depends_on:
      - product-db

  product-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_product:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=product_admin
      - POSTGRES_PASSWORD=product_admin
      - POSTGRES_DB=product_db_dev

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_config.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-service
      - product-service


volumes:
  postgres_data_product:
  postgres_data_auth:
